### ISSUE TITLE
Intellisense? 

### ISSUE THREAD

**Issue by alexdresko** [stef-levesque/vscode-autohotkey#1]
Is it planned? Is it even possible? I'd love to help if it can be done.

**Comment by stef-levesque** [comment]
Just to confirm, do you mean Simple Validation and Code Completion, as detailed in [VS Code docs](https://code.visualstudio.com/docs/extensions/example-language-server#_adding-additional-language-features) ?

If so, yes it's possible, and you are welcome to help :smiley:

**Comment by alexdresko** [comment]
Both, I suppose... Have you started down the path of implementing either feature, and do you have any thoughts or ideas that might help me get started? I can, of course, dig into the docs as I've done many times for other VSCode related things, but I haven't done anything with validation or completion....

**Comment by stef-levesque** [comment]
No, I haven't really look at it yet.
I'm not too familiar with Language Servers extensions, so I guess [docs](https://code.visualstudio.com/docs/extensions/example-language-server) and [GitHub](https://github.com/Microsoft/vscode/issues) are your best bet for now.

Although, I wonder if the AutoHotkey syntax is much friendly for static analysis.

**Comment by stef-levesque** [comment]
Closing for now. Reopen if any progress has been made.
