### ISSUE TITLE
Add option to disable snippets

### ISSUE THREAD

**Issue by jondcoleman** [stef-levesque/vscode-autohotkey#14]
I appreciate the syntax highlighting but would like to be able to disable the snippets. Thanks!

**Comment by denolfe** [comment]
The ability to disable snippets for a single extension is not a [feature](https://github.com/Microsoft/vscode/issues/10565) that VS Code has implemented yet

However, it is rather simple to remove the snippets from your installation of this extension. Simply find the extension folder, typically located in `$HOME\.vscode\extensions\slevesque.vscode-autohotkey` and simply delete the snippets folder inside.

**Comment by stef-levesque** [comment]
@denolfe is right, I can't find a graceful way on my side to disable snippets or suggestions.

Although, on VSCode side, this seems related to Microsoft/vscode#52789

**Comment by jondcoleman** [comment]
Thanks for looking into it!
