### ISSUE TITLE
Incorrect Identification as String in Send

### ISSUE THREAD

**Issue by ChaosOrdeal** [stef-levesque/vscode-autohotkey#28]
In the following line, "{end}" is incorrectly identified as a string.  Actually, as a parameter of Send, the text incorrectly identified as a string actually sends **double-quote, End key, double-quote** (which is the intended behavior), but it is identified and colored as a string (which it isn't).  I can't include color in this bug report, and decorating my snippet just made it confusing, so here's the raw text.  It should be easy to repro.  Thanks for the very useful extension.

F20::Send {Home}"{end}" video game{enter}

**Comment by ChaosOrdeal** [comment]
looks like a dead stick

**Comment by mark-wiemer** [comment]
Hey @ChaosOrdeal , you can open an issue on my fork, https://github.com/mark-wiemer/vscode-autohotkey-plus-plus, and I'll look into it 🙂
