### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by mark-wiemer** [stef-levesque/vscode-autohotkey#32]
It hasn't been touched in years, and several bugs have been fixed by other forks. It may be best for users to know that this extension is deprecated. You could point to my extension, [AutoHotkey Plus Plus](https://marketplace.visualstudio.com/items?itemName=mark-wiemer.vscode-autohotkey-plus-plus), as a replacement.

See [how to mark extensions as deprecated](https://code.visualstudio.com/updates/v1_68#_deprecated-extensions) and [my request to deprecate this extension](https://github.com/microsoft/vscode-discussions/discussions/1#discussioncomment-3081884)

If you're able to come back to this project, or transfer ownership to someone willing to maintain it (like me 😉) I'll happily rescind the request.

For now, it seems users are not getting a great experience with your extension, and it doesn't look like it'll improve any time soon.

**Comment by stef-levesque** [comment]
There isn't much in this repo, I'd rather deprecate it and forward to your extension
