### ISSUE TITLE
Wrong block comment highlight

### ISSUE THREAD

**Issue by myfonj** [stef-levesque/vscode-autohotkey#9]
> `/*` and `*/` symbols can be used to comment out an entire section, but _only if the symbols appear at the beginning of a line_ (…)

https://autohotkey.com/docs/Language.htm#comments

It has quite nasty effect that there is no such thing as `/* */` in AHK we are probably used to form other languages:
```
TTT (text)
/* CCC (comment) */ CCC
/* */ CCC
CCC */ CCC
*/ TTT
```

**Comment by myfonj** [comment]
For demonstration, current highlight:
![ahk-comment-highlight-bad 4b16c](https://user-images.githubusercontent.com/1761395/34482244-053011ce-efb7-11e7-8752-f59fd6399596.png)
Correct highlight:
![ahk-comment-highlight-good 4b16c](https://user-images.githubusercontent.com/1761395/34482245-054fa37c-efb7-11e7-8a01-ef83fd7e80db.png)

**Comment by stef-levesque** [comment]
Using the RegExp '^/\*' and '^\*/' should work then. I'll have a look at it tomorrow.

**Comment by myfonj** [comment]
Yup. It is not clearly stated in docs, but testing revealed that whitespace is not counted to _the beginning of a line_ here, just like in other tokens already in syntax. So that's why `^\s*/\*` in PR.

**Comment by myfonj** [comment]
And one other quite weird thing: unbalanced `*/` itself yields no syntax error (provided it _starts a line_) and is simply ignored if there was no `/*` above.  So perhaps it would be relevant to add such token as well.

**Comment by myfonj** [comment]
Any chance bumping this fix to the [Marketplace](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey)?

**Comment by stef-levesque** [comment]
Yes, I'll push a new release this week.
